### ISSUE TITLE
when creating new course set to use cards format - debugging error shown

### ISSUE THREAD

**Issue by danmarsden** [Vidalia/moodle-format_cards#3]
Notice: Undefined property: stdClass::$importgridimages in /moodle/course/format/cards/lib.php on line 349

**Comment by danmarsden** [comment]
also - when viewing a course - seeing this error:
Notice: Undefined property: stdClass::$hiddenfromstudents in moodle/course/format/cards/classes/output/courseformat/content/section.php on line 69

**Comment by danmarsden** [comment]
and:
Warning: Creating default object from empty value in moodle/course/format/cards/classes/output/courseformat/content/section.php on line 82

**Comment by Vidalia** [comment]
Thanks for pointing these out, should be fixed in the latest relase

**Comment by danmarsden** [comment]
hmmm - did you test this with debugging display errors = on and developer mode enabled?

I'm still getting the error... I suspect the check in update_course_format_options should be more like:
```
        if (empty($data->importgridimages) || !$this->course_has_grid_images()) {
```

**Comment by Vidalia** [comment]
Getting paranoid about missing these messages now! Should be fixed in the latest version.
